# Generated by Django 4.1.3 on 2022-12-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MVT", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="familiar", old_name="numero_pasaporte", new_name="numero_dni",
        ),
    ]
