# Generated by Django 4.1.3 on 2022-12-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MVT", "0002_rename_numero_pasaporte_familiar_numero_dni"),
    ]

    operations = [
        migrations.AddField(
            model_name="familiar",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
