# Generated by Django 4.1.3 on 2022-12-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MVT", "0004_alter_familiar_fecha_nacimiento"),
    ]

    operations = [
        migrations.RemoveField(model_name="familiar", name="fecha_nacimiento",),
    ]
