# Generated by Django 4.1.3 on 2022-12-06 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("MVT", "0005_remove_familiar_fecha_nacimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="familiar",
            name="fecha_nac",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
